### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by magicalraccoon**
Left out optional arguments.

### CODE REVIEW

**Comment by taers232c** [comment]
Sara,

In this line:
`bash <(curl -s -S -L https://git.io/vMHsV) [-l] [-d <Path>]`
the backwards quotes make the whole line appear in a grey background.

In your edit:
`bash <(curl -s -S -L https://git.io/vMHsV)` [-l] [-d <Path>]
the optional parameters would not be in a grey background.

The backwards quotes are part of the markup language, not the actual command line.

Ross

**Comment by magicalraccoon** [comment]
When the entire line is colored grey, it leads inexperienced users to copy and paste the whole string. By taking off monospaced grey from the optional items, we designate them as such.

**Comment by taers232c** [comment]
Sara,

Interesting point, how about this:

* Single Executable Archive, Automatic, Linux/Mac OS/Google Cloud Shell
  - Start a terminal session and execute one of the following commands:
  - New install, default path `$HOME/bin`
    - `bash <(curl -s -S -L https://git.io/vMHsV)`
  - New install, specify a path
    - `bash <(curl -s -S -L https://git.io/vMHsV) -d <Path>`
  - Upgrade, default path `$HOME/bin`
    - `bash <(curl -s -S -L https://git.io/vMHsV) -l`
  - Upgrade, specify a path
    - `bash <(curl -s -S -L https://git.io/vMHsV) -l -d <Path>`

Ross

**Comment by magicalraccoon** [comment]
Much more readable, thanks for taking my suggestion!

**Comment by taers232c** [comment]
I'll close this as I've added the enhanced instructions.

Thanks,

Ross

**Pull request closed without merging**
